/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './app';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/router/src/router';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/router/src/directives/router_link';
import * as import12 from '@angular/router/src/directives/router_outlet';
import * as import13 from '@angular/router/src/router_state';
import * as import14 from '@angular/common/src/location/location_strategy';
import * as import15 from '@angular/router/src/router_outlet_map';
import * as import16 from '@angular/core/src/linker/component_factory_resolver';
import * as import17 from '@angular/core/src/security';
var renderType_App_Host:import0.RenderComponentType = (null as any);
class _View_App_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _App_0_4:import3.App;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_App_Host0,renderType_App_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-app',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_App0(this.viewUtils,this.injector(0),this._appEl_0);
    this._App_0_4 = new import3.App(this.parentInjector.get(import8.Router));
    this._appEl_0.initComponent(this._App_0_4,[],compView_0);
    compView_0.create(this._App_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.App) && (0 === requestNodeIndex))) { return this._App_0_4; }
    return notFoundResult;
  }
}
function viewFactory_App_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_App_Host === (null as any))) { (renderType_App_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_App_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppNgFactory:import10.ComponentFactory<import3.App> = new import10.ComponentFactory<import3.App>('my-app',viewFactory_App_Host0,import3.App);
const styles_App:any[] = [];
var renderType_App:import0.RenderComponentType = (null as any);
class _View_App0 extends import1.AppView<import3.App> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _RouterLinkWithHref_2_3:import11.RouterLinkWithHref;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _RouterOutlet_16_5:import12.RouterOutlet;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_App0,renderType_App,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'header',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','hand hidden-sm-down');
    this.renderer.setElementAttribute(this._el_0,'id','landing-header');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_2,'href','#');
    this.renderer.setElementAttribute(this._el_2,'routerLink','/');
    this._RouterLinkWithHref_2_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import8.Router),this.parentInjector.get(import13.ActivatedRoute),this.parentInjector.get(import14.LocationStrategy));
    this._el_3 = this.renderer.createElement(this._el_2,'img',(null as any));
    this.renderer.setElementAttribute(this._el_3,'src','otb-logo.png');
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'h5',(null as any));
    this.renderer.setElementAttribute(this._el_5,'id','phrase');
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'header',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','hand hidden-md-up');
    this.renderer.setElementAttribute(this._el_9,'id','landing-header-mobile');
    this._text_10 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._text_11 = this.renderer.createText(this._el_9,'\n    ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_9,'a',(null as any));
    this.renderer.setElementAttribute(this._el_12,'href','#');
    this._el_13 = this.renderer.createElement(this._el_12,'img',(null as any));
    this.renderer.setElementAttribute(this._el_13,'src','otb-logo.png');
    this._text_14 = this.renderer.createText(this._el_9,'\n',(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_16 = this.renderer.createElement(parentRenderNode,'router-outlet',(null as any));
    this._appEl_16 = new import2.AppElement(16,(null as any),this,this._el_16);
    this._RouterOutlet_16_5 = new import12.RouterOutlet(this.parentInjector.get(import15.RouterOutletMap),this._appEl_16.vcRef,this.parentInjector.get(import16.ComponentFactoryResolver),(null as any));
    this._text_17 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_18 = this.renderer.createElement(parentRenderNode,'footer',(null as any));
    this.renderer.setElementAttribute(this._el_18,'id','copyright');
    this.renderer.setElementAttribute(this._el_18,'style','text-align:center');
    this._text_19 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'p',(null as any));
    this.renderer.setElementAttribute(this._el_20,'style','text-align: center !important');
    this._text_21 = this.renderer.createText(this._el_20,'©2016 OTB. All rights reserved.',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_18,'p',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','center');
    this._text_24 = this.renderer.createText(this._el_23,'\n        OTB\n        ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'br',(null as any));
    this._text_26 = this.renderer.createText(this._el_23,'\n        HQ in Greenville, SC\n        ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_23,'br',(null as any));
    this._text_28 = this.renderer.createText(this._el_23,'\n        (970)372-9900\n        ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_23,'br',(null as any));
    this._text_30 = this.renderer.createText(this._el_23,'\n        jonathan@otb.zone\n        ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_23,'br',(null as any));
    this._text_32 = this.renderer.createText(this._el_23,'\n        brett@otb.zone\n    ',(null as any));
    this._text_33 = this.renderer.createText(this._el_18,'\n',(null as any));
    this._text_34 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.RouterLinkWithHref) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._RouterLinkWithHref_2_3; }
    if (((token === import12.RouterOutlet) && (16 === requestNodeIndex))) { return this._RouterOutlet_16_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_2:any = '/';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._RouterLinkWithHref_2_3.routerLink = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_2_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._RouterLinkWithHref_2_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_2,'href',this.viewUtils.sanitizer.sanitize(import17.SecurityContext.URL,currVal_3));
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'',this.context.phrase,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_6,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_2_3.ngOnDestroy();
    this._RouterOutlet_16_5.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.change()) !== false);
    return (true && pd_0);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_2_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.change()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_App0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.App> {
  if ((renderType_App === (null as any))) { (renderType_App = viewUtils.createRenderComponentType('/Users/oliviatrimble/Workspaces/otb/web/app/app.html',0,import9.ViewEncapsulation.None,styles_App,{})); }
  return new _View_App0(viewUtils,parentInjector,declarationEl);
}