/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './constant-contact';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/http/src/http';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/common/src/directives/ng_if';
import * as import13 from '@angular/core/src/linker/template_ref';
import * as import14 from '@angular/router/src/directives/router_link';
import * as import15 from '@angular/router/src/router_state';
import * as import16 from '@angular/common/src/location/location_strategy';
import * as import17 from '@angular/core/src/security';
var renderType_ConstantContact_Host:import0.RenderComponentType = (null as any);
class _View_ConstantContact_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ConstantContact_0_4:import3.ConstantContact;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConstantContact_Host0,renderType_ConstantContact_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('constant-contact',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ConstantContact0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ConstantContact_0_4 = new import3.ConstantContact(this.parentInjector.get(import8.Http),this.parentInjector.get(import9.Router));
    this._appEl_0.initComponent(this._ConstantContact_0_4,[],compView_0);
    compView_0.create(this._ConstantContact_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ConstantContact) && (0 === requestNodeIndex))) { return this._ConstantContact_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ConstantContact_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ConstantContact_Host === (null as any))) { (renderType_ConstantContact_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_ConstantContact_Host0(viewUtils,parentInjector,declarationEl);
}
export const ConstantContactNgFactory:import11.ComponentFactory<import3.ConstantContact> = new import11.ComponentFactory<import3.ConstantContact>('constant-contact',viewFactory_ConstantContact_Host0,import3.ConstantContact);
const styles_ConstantContact:any[] = [];
var renderType_ConstantContact:import0.RenderComponentType = (null as any);
class _View_ConstantContact0 extends import1.AppView<import3.ConstantContact> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _anchor_61:any;
  /*private*/ _appEl_61:import2.AppElement;
  _TemplateRef_61_5:any;
  _NgIf_61_6:import12.NgIf;
  _text_62:any;
  _anchor_63:any;
  /*private*/ _appEl_63:import2.AppElement;
  _TemplateRef_63_5:any;
  _NgIf_63_6:import12.NgIf;
  _text_64:any;
  _text_65:any;
  _anchor_66:any;
  /*private*/ _appEl_66:import2.AppElement;
  _TemplateRef_66_5:any;
  _NgIf_66_6:import12.NgIf;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _anchor_70:any;
  /*private*/ _appEl_70:import2.AppElement;
  _TemplateRef_70_5:any;
  _NgIf_70_6:import12.NgIf;
  _text_71:any;
  _anchor_72:any;
  /*private*/ _appEl_72:import2.AppElement;
  _TemplateRef_72_5:any;
  _NgIf_72_6:import12.NgIf;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _text_76:any;
  _anchor_77:any;
  /*private*/ _appEl_77:import2.AppElement;
  _TemplateRef_77_5:any;
  _NgIf_77_6:import12.NgIf;
  _text_78:any;
  _anchor_79:any;
  /*private*/ _appEl_79:import2.AppElement;
  _TemplateRef_79_5:any;
  _NgIf_79_6:import12.NgIf;
  _text_80:any;
  _text_81:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConstantContact0,renderType_ConstantContact,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'section',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','p-a-3');
    this.renderer.setElementAttribute(this._el_0,'id','constant-contact');
    this._text_1 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'h2',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Constant Contact Registration',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','form-group');
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'label',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'Organization name',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_5,'input',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','form-control');
    this.renderer.setElementAttribute(this._el_10,'placeholder','your organization name');
    this.renderer.setElementAttribute(this._el_10,'type','text');
    this._text_11 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','form-group');
    this._text_14 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'label',(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Website address',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_13,'input',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','form-control');
    this.renderer.setElementAttribute(this._el_18,'placeholder','exampledomain.com');
    this.renderer.setElementAttribute(this._el_18,'type','text');
    this._text_19 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','form-group');
    this._text_22 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'label',(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n            ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'span',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','text-info');
    this._text_26 = this.renderer.createText(this._el_25,'*',(null as any));
    this._text_27 = this.renderer.createText(this._el_23,'Full name',(null as any));
    this._text_28 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_21,'input',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','form-control');
    this.renderer.setElementAttribute(this._el_29,'placeholder','your first and last name');
    this.renderer.setElementAttribute(this._el_29,'type','text');
    this._text_30 = this.renderer.createText(this._el_21,'\n    ',(null as any));
    this._text_31 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','form-group');
    this._text_33 = this.renderer.createText(this._el_32,'\n        ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_32,'label',(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'\n            ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_34,'span',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','text-info');
    this._text_37 = this.renderer.createText(this._el_36,'*',(null as any));
    this._text_38 = this.renderer.createText(this._el_34,'Email address',(null as any));
    this._text_39 = this.renderer.createText(this._el_32,'\n        ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_32,'small',(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'*Will also be used as your username for Constant Contact',(null as any));
    this._text_42 = this.renderer.createText(this._el_32,'\n        ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_32,'input',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','form-control');
    this.renderer.setElementAttribute(this._el_43,'placeholder','your email address');
    this.renderer.setElementAttribute(this._el_43,'type','text');
    this._text_44 = this.renderer.createText(this._el_32,'\n    ',(null as any));
    this._text_45 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_0,'h5',(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'Security questions',(null as any));
    this._text_48 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_0,'small',(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'\n        ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_49,'span',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','text-info');
    this._text_52 = this.renderer.createText(this._el_51,'*',(null as any));
    this._text_53 = this.renderer.createText(this._el_49,'Choose one to answer',(null as any));
    this._text_54 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_0,'form',(null as any));
    this.renderer.setElementAttribute(this._el_55,'class','m-b-1');
    this._text_56 = this.renderer.createText(this._el_55,'\n        ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_55,'div',(null as any));
    this.renderer.setElementAttribute(this._el_57,'class','dropdown open');
    this._text_58 = this.renderer.createText(this._el_57,'\n            ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_57,'button',(null as any));
    this.renderer.setElementAttribute(this._el_59,'class','btn btn-secondary dropdown-toggle');
    this.renderer.setElementAttribute(this._el_59,'id','dropdownMenuButton');
    this.renderer.setElementAttribute(this._el_59,'type','button');
    this._text_60 = this.renderer.createText(this._el_59,'\n              ',(null as any));
    this._anchor_61 = this.renderer.createTemplateAnchor(this._el_59,(null as any));
    this._appEl_61 = new import2.AppElement(61,59,this,this._anchor_61);
    this._TemplateRef_61_5 = new import13.TemplateRef_(this._appEl_61,viewFactory_ConstantContact1);
    this._NgIf_61_6 = new import12.NgIf(this._appEl_61.vcRef,this._TemplateRef_61_5);
    this._text_62 = this.renderer.createText(this._el_59,'\n              ',(null as any));
    this._anchor_63 = this.renderer.createTemplateAnchor(this._el_59,(null as any));
    this._appEl_63 = new import2.AppElement(63,59,this,this._anchor_63);
    this._TemplateRef_63_5 = new import13.TemplateRef_(this._appEl_63,viewFactory_ConstantContact2);
    this._NgIf_63_6 = new import12.NgIf(this._appEl_63.vcRef,this._TemplateRef_63_5);
    this._text_64 = this.renderer.createText(this._el_59,'\n            ',(null as any));
    this._text_65 = this.renderer.createText(this._el_57,'\n            ',(null as any));
    this._anchor_66 = this.renderer.createTemplateAnchor(this._el_57,(null as any));
    this._appEl_66 = new import2.AppElement(66,57,this,this._anchor_66);
    this._TemplateRef_66_5 = new import13.TemplateRef_(this._appEl_66,viewFactory_ConstantContact3);
    this._NgIf_66_6 = new import12.NgIf(this._appEl_66.vcRef,this._TemplateRef_66_5);
    this._text_67 = this.renderer.createText(this._el_57,'\n        ',(null as any));
    this._text_68 = this.renderer.createText(this._el_55,'\n    ',(null as any));
    this._text_69 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._anchor_70 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_70 = new import2.AppElement(70,0,this,this._anchor_70);
    this._TemplateRef_70_5 = new import13.TemplateRef_(this._appEl_70,viewFactory_ConstantContact4);
    this._NgIf_70_6 = new import12.NgIf(this._appEl_70.vcRef,this._TemplateRef_70_5);
    this._text_71 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_72 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_72 = new import2.AppElement(72,0,this,this._anchor_72);
    this._TemplateRef_72_5 = new import13.TemplateRef_(this._appEl_72,viewFactory_ConstantContact5);
    this._NgIf_72_6 = new import12.NgIf(this._appEl_72.vcRef,this._TemplateRef_72_5);
    this._text_73 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_74 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_74,'class','btn btn-outline-info btn-block p-a-1');
    this._text_75 = this.renderer.createText(this._el_74,'Create my account',(null as any));
    this._text_76 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._anchor_77 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_77 = new import2.AppElement(77,0,this,this._anchor_77);
    this._TemplateRef_77_5 = new import13.TemplateRef_(this._appEl_77,viewFactory_ConstantContact6);
    this._NgIf_77_6 = new import12.NgIf(this._appEl_77.vcRef,this._TemplateRef_77_5);
    this._text_78 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_79 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_79 = new import2.AppElement(79,0,this,this._anchor_79);
    this._TemplateRef_79_5 = new import13.TemplateRef_(this._appEl_79,viewFactory_ConstantContact7);
    this._NgIf_79_6 = new import12.NgIf(this._appEl_79.vcRef,this._TemplateRef_79_5);
    this._text_80 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_81 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_10,'input',this.eventHandler(this._handle_input_10_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_18,'input',this.eventHandler(this._handle_input_18_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_29,'input',this.eventHandler(this._handle_input_29_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_43,'input',this.eventHandler(this._handle_input_43_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_59,'click',this.eventHandler(this._handle_click_59_0.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_74,'click',this.eventHandler(this._handle_click_74_0.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._anchor_61,
      this._text_62,
      this._anchor_63,
      this._text_64,
      this._text_65,
      this._anchor_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._anchor_70,
      this._text_71,
      this._anchor_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._text_76,
      this._anchor_77,
      this._text_78,
      this._anchor_79,
      this._text_80,
      this._text_81
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.TemplateRef) && (61 === requestNodeIndex))) { return this._TemplateRef_61_5; }
    if (((token === import12.NgIf) && (61 === requestNodeIndex))) { return this._NgIf_61_6; }
    if (((token === import13.TemplateRef) && (63 === requestNodeIndex))) { return this._TemplateRef_63_5; }
    if (((token === import12.NgIf) && (63 === requestNodeIndex))) { return this._NgIf_63_6; }
    if (((token === import13.TemplateRef) && (66 === requestNodeIndex))) { return this._TemplateRef_66_5; }
    if (((token === import12.NgIf) && (66 === requestNodeIndex))) { return this._NgIf_66_6; }
    if (((token === import13.TemplateRef) && (70 === requestNodeIndex))) { return this._TemplateRef_70_5; }
    if (((token === import12.NgIf) && (70 === requestNodeIndex))) { return this._NgIf_70_6; }
    if (((token === import13.TemplateRef) && (72 === requestNodeIndex))) { return this._TemplateRef_72_5; }
    if (((token === import12.NgIf) && (72 === requestNodeIndex))) { return this._NgIf_72_6; }
    if (((token === import13.TemplateRef) && (77 === requestNodeIndex))) { return this._TemplateRef_77_5; }
    if (((token === import12.NgIf) && (77 === requestNodeIndex))) { return this._NgIf_77_6; }
    if (((token === import13.TemplateRef) && (79 === requestNodeIndex))) { return this._TemplateRef_79_5; }
    if (((token === import12.NgIf) && (79 === requestNodeIndex))) { return this._NgIf_79_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_9:any = (this.context.data.security.question == (0 - 1));
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgIf_61_6.ngIf = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = (this.context.data.security.question > (0 - 1));
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgIf_63_6.ngIf = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this.context.showDropdown;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgIf_66_6.ngIf = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = (this.context.data.security.question > (0 - 1));
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgIf_70_6.ngIf = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this.context.processing;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgIf_72_6.ngIf = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_16:any = this.context.showSuccess;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._NgIf_77_6.ngIf = currVal_16;
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this.context.showError;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._NgIf_79_6.ngIf = currVal_17;
      this._expr_17 = currVal_17;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.context.data.organization;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_10,'value',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_3:any = this.context.data.website;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementProperty(this._el_18,'value',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = this.context.data.name;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_29,'value',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = this.context.data.email;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementProperty(this._el_43,'value',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_15:any = this.context.processing;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementProperty(this._el_74,'disabled',currVal_15);
      this._expr_15 = currVal_15;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_input_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.data.organization = $event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_input_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.data.website = $event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_input_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.data.name = $event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_input_43_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.data.email = $event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_click_59_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.toggleDropdown()) !== false);
    return (true && pd_0);
  }
  private _handle_click_74_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.sendForm()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ConstantContact0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ConstantContact> {
  if ((renderType_ConstantContact === (null as any))) { (renderType_ConstantContact = viewUtils.createRenderComponentType('/Users/oliviatrimble/Workspaces/otb/web/app/pages/constant-contact/constant-contact.html',0,import10.ViewEncapsulation.None,styles_ConstantContact,{})); }
  return new _View_ConstantContact0(viewUtils,parentInjector,declarationEl);
}
class _View_ConstantContact1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConstantContact1,renderType_ConstantContact,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Select a security question',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_ConstantContact1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ConstantContact1(viewUtils,parentInjector,declarationEl);
}
class _View_ConstantContact2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConstantContact2,renderType_ConstantContact,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.questions[this.parent.context.data.security.question],'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ConstantContact2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ConstantContact2(viewUtils,parentInjector,declarationEl);
}
class _View_ConstantContact3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConstantContact3,renderType_ConstantContact,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','dropdown-menu');
    this._text_1 = this.renderer.createText(this._el_0,'\n                  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','btn btn-outline-secondary d-block');
    this.renderer.setElementAttribute(this._el_2,'style','text-align: left');
    this._text_3 = this.renderer.createText(this._el_2,'\n                  Where was your first Job?',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','btn btn-outline-secondary d-block');
    this.renderer.setElementAttribute(this._el_5,'style','text-align: left');
    this._text_6 = this.renderer.createText(this._el_5,'\n                  What was your first phone number?\n              ',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n\n              ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','btn btn-outline-secondary d-block');
    this.renderer.setElementAttribute(this._el_8,'style','text-align: left');
    this._text_9 = this.renderer.createText(this._el_8,'\n                  What was your first teacher\'s name?\n              ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','btn btn-outline-secondary d-block');
    this.renderer.setElementAttribute(this._el_11,'style','text-align: left');
    this._text_12 = this.renderer.createText(this._el_11,'\n                  Who was your best childhood friend?\n              ',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n              ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','btn btn-outline-secondary d-block');
    this.renderer.setElementAttribute(this._el_14,'style','text-align: left');
    this._text_15 = this.renderer.createText(this._el_14,'\n                  What is your father\'s middle name?\n              ',(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_14,'click',this.eventHandler(this._handle_click_14_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[]);
    return (null as any);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.test(0)) !== false);
    return (true && pd_0);
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.test(1)) !== false);
    return (true && pd_0);
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.test(2)) !== false);
    return (true && pd_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.test(3)) !== false);
    return (true && pd_0);
  }
  private _handle_click_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.test(4)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ConstantContact3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ConstantContact3(viewUtils,parentInjector,declarationEl);
}
class _View_ConstantContact4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConstantContact4,renderType_ConstantContact,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','form-group');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'label',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'span',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','text-info');
    this._text_5 = this.renderer.createText(this._el_4,'*',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'input',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','form-control');
    this.renderer.setElementAttribute(this._el_8,'id','contactInput');
    this.renderer.setElementAttribute(this._el_8,'placeholder','your answer');
    this.renderer.setElementAttribute(this._el_8,'type','text');
    this._text_9 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_8,'input',this.eventHandler(this._handle_input_8_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.questions[this.parent.context.data.security.question],'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_6,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_2:any = this.parent.context.data.security.answer;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_8,'value',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_input_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.data.security.answer = $event.target.value)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ConstantContact4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ConstantContact4(viewUtils,parentInjector,declarationEl);
}
class _View_ConstantContact5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConstantContact5,renderType_ConstantContact,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'small',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','p-t-2 text-light');
    this._text_1 = this.renderer.createText(this._el_0,'Processing.........',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_ConstantContact5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ConstantContact5(viewUtils,parentInjector,declarationEl);
}
class _View_ConstantContact6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _RouterLinkWithHref_12_3:import14.RouterLinkWithHref;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConstantContact6,renderType_ConstantContact,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'aside',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','modal toast');
    this.renderer.setElementAttribute(this._el_0,'role','dialog');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','modal-dialog modal-md');
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','modal-content p-a-2 bg-info center');
    this._text_5 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'p',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','text-light weight-500');
    this._text_7 = this.renderer.createText(this._el_6,'\n                    Thank you! An account will be created with the username\n                    ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'span',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','text-danger');
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'. You will receive a confirmation email when processing is complete containing your login information as a reminder. Please contact us if you have further questions at jonathan@otb.zone\n                ',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_4,'a',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','btn btn-outline-danger');
    this.renderer.setElementAttribute(this._el_12,'routerLink','/');
    this._RouterLinkWithHref_12_3 = new import14.RouterLinkWithHref(this.parent.parentInjector.get(import9.Router),this.parent.parentInjector.get(import15.ActivatedRoute),this.parent.parentInjector.get(import16.LocationStrategy));
    this._text_13 = this.renderer.createText(this._el_12,'Dismiss',(null as any));
    this._text_14 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._text_15 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_16 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.RouterLinkWithHref) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._RouterLinkWithHref_12_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_3:any = '/';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._RouterLinkWithHref_12_3.routerLink = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_12_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.data.email,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_9,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_4:any = this._RouterLinkWithHref_12_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_12,'href',this.viewUtils.sanitizer.sanitize(import17.SecurityContext.URL,currVal_4));
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_12_3.ngOnDestroy();
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.dismiss()) !== false);
    const pd_1:any = ((<any>this._RouterLinkWithHref_12_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_ConstantContact6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ConstantContact6(viewUtils,parentInjector,declarationEl);
}
class _View_ConstantContact7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ConstantContact7,renderType_ConstantContact,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'aside',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','modal toast');
    this.renderer.setElementAttribute(this._el_0,'role','dialog');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','modal-dialog modal-md');
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','modal-content p-a-2 bg-info center');
    this._text_5 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'p',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','text-light weight-500');
    this._text_7 = this.renderer.createText(this._el_6,'\n                    Whoops, an error has occured, please make sure you entered everything correctly and try again.\n                ',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._text_9 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_10 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_11 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._text_11
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_ConstantContact7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ConstantContact7(viewUtils,parentInjector,declarationEl);
}