/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './landing';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/http/src/http';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/common/src/directives/ng_if';
import * as import12 from '@angular/core/src/linker/template_ref';
var renderType_Landing_Host:import0.RenderComponentType = (null as any);
class _View_Landing_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Landing_0_4:import3.Landing;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Landing_Host0,renderType_Landing_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('landing',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Landing0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Landing_0_4 = new import3.Landing(this.parentInjector.get(import8.Http));
    this._appEl_0.initComponent(this._Landing_0_4,[],compView_0);
    compView_0.create(this._Landing_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.Landing) && (0 === requestNodeIndex))) { return this._Landing_0_4; }
    return notFoundResult;
  }
}
function viewFactory_Landing_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_Landing_Host === (null as any))) { (renderType_Landing_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_Landing_Host0(viewUtils,parentInjector,declarationEl);
}
export const LandingNgFactory:import10.ComponentFactory<import3.Landing> = new import10.ComponentFactory<import3.Landing>('landing',viewFactory_Landing_Host0,import3.Landing);
const styles_Landing:any[] = [];
var renderType_Landing:import0.RenderComponentType = (null as any);
class _View_Landing0 extends import1.AppView<import3.Landing> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _el_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _text_94:any;
  _text_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _el_99:any;
  _text_100:any;
  _el_101:any;
  _text_102:any;
  _el_103:any;
  _text_104:any;
  _text_105:any;
  _text_106:any;
  _text_107:any;
  _el_108:any;
  _text_109:any;
  _el_110:any;
  _text_111:any;
  _el_112:any;
  _text_113:any;
  _el_114:any;
  _text_115:any;
  _el_116:any;
  _text_117:any;
  _el_118:any;
  _text_119:any;
  _text_120:any;
  _text_121:any;
  _el_122:any;
  _text_123:any;
  _text_124:any;
  _text_125:any;
  _text_126:any;
  _text_127:any;
  _el_128:any;
  _text_129:any;
  _el_130:any;
  _text_131:any;
  _el_132:any;
  _text_133:any;
  _el_134:any;
  _text_135:any;
  _el_136:any;
  _text_137:any;
  _text_138:any;
  _el_139:any;
  _text_140:any;
  _text_141:any;
  _text_142:any;
  _text_143:any;
  _text_144:any;
  _el_145:any;
  _text_146:any;
  _el_147:any;
  _text_148:any;
  _el_149:any;
  _text_150:any;
  _el_151:any;
  _text_152:any;
  _el_153:any;
  _text_154:any;
  _text_155:any;
  _el_156:any;
  _text_157:any;
  _text_158:any;
  _text_159:any;
  _text_160:any;
  _text_161:any;
  _text_162:any;
  _text_163:any;
  _text_164:any;
  _anchor_165:any;
  /*private*/ _appEl_165:import2.AppElement;
  _TemplateRef_165_5:any;
  _NgIf_165_6:import11.NgIf;
  _text_166:any;
  _anchor_167:any;
  /*private*/ _appEl_167:import2.AppElement;
  _TemplateRef_167_5:any;
  _NgIf_167_6:import11.NgIf;
  _text_168:any;
  _text_169:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Landing0,renderType_Landing,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'section',(null as any));
    this.renderer.setElementAttribute(this._el_0,'id','landing');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'section',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','wrapper');
    this.renderer.setElementAttribute(this._el_2,'id','services');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','container');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'header',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','center');
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'h1',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','text-info');
    this._text_9 = this.renderer.createText(this._el_8,'Solutions',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','row solutions');
    this._text_13 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','col-lg-4');
    this._text_15 = this.renderer.createText(this._el_14,'\n                    ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'div',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','card');
    this._text_17 = this.renderer.createText(this._el_16,'\n                        ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'header',(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'\n                            ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'h3',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','center');
    this._text_21 = this.renderer.createText(this._el_20,'Hybrid App Development',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n                            ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_18,'span',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','center text-muted');
    this._text_24 = this.renderer.createText(this._el_23,'Launch off fast',(null as any));
    this._text_25 = this.renderer.createText(this._el_18,'\n                            ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_18,'span',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','p-a-1 mega-octicon octicon-rocket text-danger');
    this._text_27 = this.renderer.createText(this._el_18,'\n                        ',(null as any));
    this._text_28 = this.renderer.createText(this._el_16,'\n                        ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_16,'p',(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'Leveraging modern technologies, our team crafts high quality mobile, desktop and web apps with tremendous code share. This allows us to get your app rolled out on multiple platforms in fractions of the time.',(null as any));
    this._text_31 = this.renderer.createText(this._el_16,'\n                        ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_16,'p',(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'Custom built for you, everything you want, nothing you don\'t. Trust us, we love cookies, but skip those cookie cutter solutions. If you want your app to stand out from the pack, you are in the right place! We take the time to understand\n                            your needs and come up with the best solution for the job at hand.',(null as any));
    this._text_34 = this.renderer.createText(this._el_16,'\n                    ',(null as any));
    this._text_35 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._text_36 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','col-lg-4');
    this._text_38 = this.renderer.createText(this._el_37,'\n                    ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'div',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','card');
    this._text_40 = this.renderer.createText(this._el_39,'\n                        ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_39,'header',(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'\n                            ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_41,'h3',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','center');
    this._text_44 = this.renderer.createText(this._el_43,'Graphic Design',(null as any));
    this._text_45 = this.renderer.createText(this._el_41,'\n                            ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_41,'span',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','center text-muted');
    this._text_47 = this.renderer.createText(this._el_46,'Dreams should be beautiful',(null as any));
    this._text_48 = this.renderer.createText(this._el_41,'\n                            ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_41,'span',(null as any));
    this.renderer.setElementAttribute(this._el_49,'class','p-a-1 mega-octicon octicon-paintcan text-danger');
    this._text_50 = this.renderer.createText(this._el_41,'\n                        ',(null as any));
    this._text_51 = this.renderer.createText(this._el_39,'\n                        ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_39,'p',(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'Graphic design is way more than making a “pretty billboard” or playing around with Photoshop all day.” It is a way to reach consumers of all ages, colors and backgrounds. Graphic design allows us to reach consumers by increasing\n                            brand awareness as well as helping to form last relations between consumers and businesses. As elementary as it may sound, visual communication simplifies life.',(null as any));
    this._text_54 = this.renderer.createText(this._el_39,'\n                    ',(null as any));
    this._text_55 = this.renderer.createText(this._el_37,'\n                ',(null as any));
    this._text_56 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_57,'class','col-lg-4');
    this._text_58 = this.renderer.createText(this._el_57,'\n                    ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_57,'div',(null as any));
    this.renderer.setElementAttribute(this._el_59,'class','card');
    this._text_60 = this.renderer.createText(this._el_59,'\n                        ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_59,'header',(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'\n                            ',(null as any));
    this._el_63 = this.renderer.createElement(this._el_61,'h3',(null as any));
    this.renderer.setElementAttribute(this._el_63,'class','center');
    this._text_64 = this.renderer.createText(this._el_63,'Services',(null as any));
    this._text_65 = this.renderer.createText(this._el_61,'\n                            ',(null as any));
    this._el_66 = this.renderer.createElement(this._el_61,'span',(null as any));
    this.renderer.setElementAttribute(this._el_66,'class','center text-muted');
    this._text_67 = this.renderer.createText(this._el_66,'We\'ve got you covered',(null as any));
    this._text_68 = this.renderer.createText(this._el_61,'\n                            ',(null as any));
    this._el_69 = this.renderer.createElement(this._el_61,'span',(null as any));
    this.renderer.setElementAttribute(this._el_69,'class','p-a-1 mega-octicon octicon-plug text-danger');
    this._text_70 = this.renderer.createText(this._el_61,'\n                        ',(null as any));
    this._text_71 = this.renderer.createText(this._el_59,'\n                        ',(null as any));
    this._el_72 = this.renderer.createElement(this._el_59,'p',(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'Integrations.... Does your team use a CMS, CRM or Online Accounting Tool? Chances are we can take your integrations to the next level to streamline your business by maximizing your productivity. We are a constant contact partner.',(null as any));
    this._text_74 = this.renderer.createText(this._el_59,'\n                    ',(null as any));
    this._text_75 = this.renderer.createText(this._el_57,'\n                ',(null as any));
    this._text_76 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._text_77 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_78 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_79 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_80 = this.renderer.createElement(this._el_0,'section',(null as any));
    this.renderer.setElementAttribute(this._el_80,'class','wrapper brand-inverse-bg');
    this._text_81 = this.renderer.createText(this._el_80,'\n        ',(null as any));
    this._el_82 = this.renderer.createElement(this._el_80,'div',(null as any));
    this.renderer.setElementAttribute(this._el_82,'class','container');
    this._text_83 = this.renderer.createText(this._el_82,'\n            ',(null as any));
    this._el_84 = this.renderer.createElement(this._el_82,'header',(null as any));
    this._text_85 = this.renderer.createText(this._el_84,'\n                ',(null as any));
    this._el_86 = this.renderer.createElement(this._el_84,'h1',(null as any));
    this.renderer.setElementAttribute(this._el_86,'class','center');
    this._text_87 = this.renderer.createText(this._el_86,'Like what you see?',(null as any));
    this._text_88 = this.renderer.createText(this._el_84,'\n            ',(null as any));
    this._text_89 = this.renderer.createText(this._el_82,'\n            ',(null as any));
    this._el_90 = this.renderer.createElement(this._el_82,'p',(null as any));
    this.renderer.setElementAttribute(this._el_90,'class','center');
    this._text_91 = this.renderer.createText(this._el_90,'Don\'t hesitate to get in touch with us, by clicking the button below, or if you prefer give us a call at (970)372-9900. We are open around the clock, based out of the east coast.\n\n            ',(null as any));
    this._el_92 = this.renderer.createElement(this._el_90,'button',(null as any));
    this.renderer.setElementAttribute(this._el_92,'class','btn btn-outline-danger btn-big center m-t-2');
    this._text_93 = this.renderer.createText(this._el_92,'Hire us',(null as any));
    this._text_94 = this.renderer.createText(this._el_90,'\n        ',(null as any));
    this._text_95 = this.renderer.createText(this._el_80,'\n    ',(null as any));
    this._text_96 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_97 = this.renderer.createElement(this._el_0,'section',(null as any));
    this.renderer.setElementAttribute(this._el_97,'class','wrapper bg-info');
    this.renderer.setElementAttribute(this._el_97,'id','team');
    this._text_98 = this.renderer.createText(this._el_97,'\n        ',(null as any));
    this._el_99 = this.renderer.createElement(this._el_97,'div',(null as any));
    this.renderer.setElementAttribute(this._el_99,'class','container');
    this._text_100 = this.renderer.createText(this._el_99,'\n            ',(null as any));
    this._el_101 = this.renderer.createElement(this._el_99,'header',(null as any));
    this._text_102 = this.renderer.createText(this._el_101,'\n                ',(null as any));
    this._el_103 = this.renderer.createElement(this._el_101,'h1',(null as any));
    this.renderer.setElementAttribute(this._el_103,'class','center text-light');
    this._text_104 = this.renderer.createText(this._el_103,'Meet the team',(null as any));
    this._text_105 = this.renderer.createText(this._el_101,'\n            ',(null as any));
    this._text_106 = this.renderer.createText(this._el_99,'\n            ',(null as any));
    this._text_107 = this.renderer.createText(this._el_99,'\n            ',(null as any));
    this._el_108 = this.renderer.createElement(this._el_99,'div',(null as any));
    this.renderer.setElementAttribute(this._el_108,'class','row');
    this._text_109 = this.renderer.createText(this._el_108,'\n                ',(null as any));
    this._el_110 = this.renderer.createElement(this._el_108,'div',(null as any));
    this.renderer.setElementAttribute(this._el_110,'class','col-md-6 col-lg-4');
    this._text_111 = this.renderer.createText(this._el_110,'\n                    ',(null as any));
    this._el_112 = this.renderer.createElement(this._el_110,'div',(null as any));
    this.renderer.setElementAttribute(this._el_112,'class','card bg-danger');
    this._text_113 = this.renderer.createText(this._el_112,'\n                        ',(null as any));
    this._el_114 = this.renderer.createElement(this._el_112,'img',(null as any));
    this.renderer.setElementAttribute(this._el_114,'class','card-img-top');
    this.renderer.setElementAttribute(this._el_114,'src','resources/images/jonathan.png');
    this.renderer.setElementAttribute(this._el_114,'width','100%');
    this._text_115 = this.renderer.createText(this._el_112,'\n                        ',(null as any));
    this._el_116 = this.renderer.createElement(this._el_112,'div',(null as any));
    this.renderer.setElementAttribute(this._el_116,'class','card-block');
    this._text_117 = this.renderer.createText(this._el_116,'\n                            ',(null as any));
    this._el_118 = this.renderer.createElement(this._el_116,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_118,'class','card-title');
    this._text_119 = this.renderer.createText(this._el_118,'Jonathan Hairgrove',(null as any));
    this._text_120 = this.renderer.createText(this._el_116,'\n                            ',(null as any));
    this._text_121 = this.renderer.createText(this._el_116,'\n                            ',(null as any));
    this._el_122 = this.renderer.createElement(this._el_116,'p',(null as any));
    this.renderer.setElementAttribute(this._el_122,'class','card-text');
    this._text_123 = this.renderer.createText(this._el_122,'\n                                Years of sales and technology experience. Jonathan is the gateway to your business\' success.\n                            ',(null as any));
    this._text_124 = this.renderer.createText(this._el_116,'\n                        ',(null as any));
    this._text_125 = this.renderer.createText(this._el_112,'\n                    ',(null as any));
    this._text_126 = this.renderer.createText(this._el_110,'\n                ',(null as any));
    this._text_127 = this.renderer.createText(this._el_108,'\n                ',(null as any));
    this._el_128 = this.renderer.createElement(this._el_108,'div',(null as any));
    this.renderer.setElementAttribute(this._el_128,'class','col-md-6 col-lg-4');
    this._text_129 = this.renderer.createText(this._el_128,'\n                    ',(null as any));
    this._el_130 = this.renderer.createElement(this._el_128,'div',(null as any));
    this.renderer.setElementAttribute(this._el_130,'class','card bg-danger');
    this._text_131 = this.renderer.createText(this._el_130,'\n                        ',(null as any));
    this._el_132 = this.renderer.createElement(this._el_130,'img',(null as any));
    this.renderer.setElementAttribute(this._el_132,'class','card-img-top');
    this.renderer.setElementAttribute(this._el_132,'src','resources/images/brett.jpeg');
    this.renderer.setElementAttribute(this._el_132,'width','100%');
    this._text_133 = this.renderer.createText(this._el_130,'\n                        ',(null as any));
    this._el_134 = this.renderer.createElement(this._el_130,'div',(null as any));
    this.renderer.setElementAttribute(this._el_134,'class','card-block');
    this._text_135 = this.renderer.createText(this._el_134,' \\\n                            ',(null as any));
    this._el_136 = this.renderer.createElement(this._el_134,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_136,'class','card-title');
    this._text_137 = this.renderer.createText(this._el_136,'Brett Stetson',(null as any));
    this._text_138 = this.renderer.createText(this._el_134,'\n                            ',(null as any));
    this._el_139 = this.renderer.createElement(this._el_134,'p',(null as any));
    this.renderer.setElementAttribute(this._el_139,'class','card-text');
    this._text_140 = this.renderer.createText(this._el_139,'\n                              Full-stack developer with a passion for javascript, the open source realm and modern web frameworks.\n                            ',(null as any));
    this._text_141 = this.renderer.createText(this._el_134,'\n                        ',(null as any));
    this._text_142 = this.renderer.createText(this._el_130,'\n                    ',(null as any));
    this._text_143 = this.renderer.createText(this._el_128,'\n                ',(null as any));
    this._text_144 = this.renderer.createText(this._el_108,'\n                ',(null as any));
    this._el_145 = this.renderer.createElement(this._el_108,'div',(null as any));
    this.renderer.setElementAttribute(this._el_145,'class','col-md-6 col-lg-4 offset-md-3 offset-lg-0');
    this._text_146 = this.renderer.createText(this._el_145,'\n                    ',(null as any));
    this._el_147 = this.renderer.createElement(this._el_145,'div',(null as any));
    this.renderer.setElementAttribute(this._el_147,'class','card bg-danger');
    this._text_148 = this.renderer.createText(this._el_147,'\n                        ',(null as any));
    this._el_149 = this.renderer.createElement(this._el_147,'img',(null as any));
    this.renderer.setElementAttribute(this._el_149,'class','card-img-top');
    this.renderer.setElementAttribute(this._el_149,'src','resources/images/olivia.jpg');
    this.renderer.setElementAttribute(this._el_149,'width','100%');
    this._text_150 = this.renderer.createText(this._el_147,'\n                        ',(null as any));
    this._el_151 = this.renderer.createElement(this._el_147,'div',(null as any));
    this.renderer.setElementAttribute(this._el_151,'class','card-block');
    this._text_152 = this.renderer.createText(this._el_151,'\n                            ',(null as any));
    this._el_153 = this.renderer.createElement(this._el_151,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_153,'class','card-title');
    this._text_154 = this.renderer.createText(this._el_153,'Olivia Trimble',(null as any));
    this._text_155 = this.renderer.createText(this._el_151,'\n                            ',(null as any));
    this._el_156 = this.renderer.createElement(this._el_151,'p',(null as any));
    this.renderer.setElementAttribute(this._el_156,'class','card-text');
    this._text_157 = this.renderer.createText(this._el_156,'\n                                Graphic design + marketing and social media.\n                            ',(null as any));
    this._text_158 = this.renderer.createText(this._el_151,'\n                        ',(null as any));
    this._text_159 = this.renderer.createText(this._el_147,'\n                    ',(null as any));
    this._text_160 = this.renderer.createText(this._el_145,'\n                ',(null as any));
    this._text_161 = this.renderer.createText(this._el_108,'\n            ',(null as any));
    this._text_162 = this.renderer.createText(this._el_99,'\n        ',(null as any));
    this._text_163 = this.renderer.createText(this._el_97,'\n    ',(null as any));
    this._text_164 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_165 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_165 = new import2.AppElement(165,0,this,this._anchor_165);
    this._TemplateRef_165_5 = new import12.TemplateRef_(this._appEl_165,viewFactory_Landing1);
    this._NgIf_165_6 = new import11.NgIf(this._appEl_165.vcRef,this._TemplateRef_165_5);
    this._text_166 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_167 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_167 = new import2.AppElement(167,0,this,this._anchor_167);
    this._TemplateRef_167_5 = new import12.TemplateRef_(this._appEl_167,viewFactory_Landing2);
    this._NgIf_167_6 = new import11.NgIf(this._appEl_167.vcRef,this._TemplateRef_167_5);
    this._text_168 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_169 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_92,'click',this.eventHandler(this._handle_click_92_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._text_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._el_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._text_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._el_99,
      this._text_100,
      this._el_101,
      this._text_102,
      this._el_103,
      this._text_104,
      this._text_105,
      this._text_106,
      this._text_107,
      this._el_108,
      this._text_109,
      this._el_110,
      this._text_111,
      this._el_112,
      this._text_113,
      this._el_114,
      this._text_115,
      this._el_116,
      this._text_117,
      this._el_118,
      this._text_119,
      this._text_120,
      this._text_121,
      this._el_122,
      this._text_123,
      this._text_124,
      this._text_125,
      this._text_126,
      this._text_127,
      this._el_128,
      this._text_129,
      this._el_130,
      this._text_131,
      this._el_132,
      this._text_133,
      this._el_134,
      this._text_135,
      this._el_136,
      this._text_137,
      this._text_138,
      this._el_139,
      this._text_140,
      this._text_141,
      this._text_142,
      this._text_143,
      this._text_144,
      this._el_145,
      this._text_146,
      this._el_147,
      this._text_148,
      this._el_149,
      this._text_150,
      this._el_151,
      this._text_152,
      this._el_153,
      this._text_154,
      this._text_155,
      this._el_156,
      this._text_157,
      this._text_158,
      this._text_159,
      this._text_160,
      this._text_161,
      this._text_162,
      this._text_163,
      this._text_164,
      this._anchor_165,
      this._text_166,
      this._anchor_167,
      this._text_168,
      this._text_169
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (165 === requestNodeIndex))) { return this._TemplateRef_165_5; }
    if (((token === import11.NgIf) && (165 === requestNodeIndex))) { return this._NgIf_165_6; }
    if (((token === import12.TemplateRef) && (167 === requestNodeIndex))) { return this._TemplateRef_167_5; }
    if (((token === import11.NgIf) && (167 === requestNodeIndex))) { return this._NgIf_167_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.context.showForm;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_165_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.context.showSuccess;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_167_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_92_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.showForm = true)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Landing0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.Landing> {
  if ((renderType_Landing === (null as any))) { (renderType_Landing = viewUtils.createRenderComponentType('/Users/oliviatrimble/Workspaces/otb/web/app/pages/landing/landing.html',0,import9.ViewEncapsulation.None,styles_Landing,{})); }
  return new _View_Landing0(viewUtils,parentInjector,declarationEl);
}
class _View_Landing1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Landing1,renderType_Landing,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','modal');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','modal-dialog');
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','modal-content');
    this._text_5 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','modal-header');
    this._text_7 = this.renderer.createText(this._el_6,'\n                    ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'button',(null as any));
    this.renderer.setElementAttribute(this._el_8,'aria-label','Close');
    this.renderer.setElementAttribute(this._el_8,'class','close');
    this.renderer.setElementAttribute(this._el_8,'type','button');
    this._text_9 = this.renderer.createText(this._el_8,'\n                        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'span',(null as any));
    this.renderer.setElementAttribute(this._el_10,'aria-hidden','true');
    this._text_11 = this.renderer.createText(this._el_10,'×',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n                    ',(null as any));
    this._text_13 = this.renderer.createText(this._el_6,'\n                    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_6,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','modal-title');
    this._text_15 = this.renderer.createText(this._el_14,'We look forward to working with you!',(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','modal-body');
    this._text_19 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','form-group');
    this._text_21 = this.renderer.createText(this._el_20,'\n                        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'label',(null as any));
    this.renderer.setElementAttribute(this._el_22,'for','exampleInputEmail1');
    this._text_23 = this.renderer.createText(this._el_22,'What is your name?',(null as any));
    this._text_24 = this.renderer.createText(this._el_20,'\n                        ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_20,'input',(null as any));
    this.renderer.setElementAttribute(this._el_25,'aria-describedby','emailHelp');
    this.renderer.setElementAttribute(this._el_25,'class','form-control');
    this.renderer.setElementAttribute(this._el_25,'id','exampleInputEmail1');
    this.renderer.setElementAttribute(this._el_25,'placeholder','your name');
    this.renderer.setElementAttribute(this._el_25,'type','text');
    this._text_26 = this.renderer.createText(this._el_20,'\n                    ',(null as any));
    this._text_27 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_18,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','form-group');
    this._text_29 = this.renderer.createText(this._el_28,'\n                        ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'label',(null as any));
    this.renderer.setElementAttribute(this._el_30,'for','contactInput');
    this._text_31 = this.renderer.createText(this._el_30,'How can we reach you?',(null as any));
    this._text_32 = this.renderer.createText(this._el_28,'\n                        ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_28,'input',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','form-control');
    this.renderer.setElementAttribute(this._el_33,'id','contactInput');
    this.renderer.setElementAttribute(this._el_33,'placeholder','your email or phone');
    this.renderer.setElementAttribute(this._el_33,'type','text');
    this._text_34 = this.renderer.createText(this._el_28,'\n                    ',(null as any));
    this._text_35 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_18,'div',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','form-group');
    this._text_37 = this.renderer.createText(this._el_36,'\n                        ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'label',(null as any));
    this.renderer.setElementAttribute(this._el_38,'for','aboutInput');
    this._text_39 = this.renderer.createText(this._el_38,'Tell us about your project, or problem you need solved?',(null as any));
    this._text_40 = this.renderer.createText(this._el_36,'\n                        ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_36,'textarea',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','form-control');
    this.renderer.setElementAttribute(this._el_41,'id','aboutInput');
    this.renderer.setElementAttribute(this._el_41,'placeholder','your project');
    this.renderer.setElementAttribute(this._el_41,'rows','4');
    this._text_42 = this.renderer.createText(this._el_36,'\n                    ',(null as any));
    this._text_43 = this.renderer.createText(this._el_18,'\n                    ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_18,'button',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','btn btn-outline-danger btn-block p-a-1');
    this._text_45 = this.renderer.createText(this._el_44,'Submit',(null as any));
    this._text_46 = this.renderer.createText(this._el_18,'\n                ',(null as any));
    this._text_47 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_48 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_49 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_25,'input',this.eventHandler(this._handle_input_25_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_33,'input',this.eventHandler(this._handle_input_33_0.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_41,'input',this.eventHandler(this._handle_input_41_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_44,'click',this.eventHandler(this._handle_click_44_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this.parent.context.formData.name;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_25,'value',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = this.parent.context.formData.email;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_33,'value',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this.parent.context.formData.about;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementProperty(this._el_41,'value',currVal_6);
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.showForm = false)) !== false);
    return (true && pd_0);
  }
  private _handle_input_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.formData.name = $event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_input_33_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.formData.email = $event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_input_41_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.formData.about = $event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_click_44_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.sendForm()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Landing1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_Landing1(viewUtils,parentInjector,declarationEl);
}
class _View_Landing2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Landing2,renderType_Landing,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'aside',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','modal toast');
    this.renderer.setElementAttribute(this._el_0,'role','dialog');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','modal-dialog modal-md');
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','modal-content p-a-2 bg-danger center');
    this._text_5 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'p',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','text-light weight-500');
    this._text_7 = this.renderer.createText(this._el_6,'\n                    Thank you, we will get back to you within the next 48 hours!\n                ',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'span',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','mega-octicon octicon-clock');
    this._text_10 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_Landing2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_Landing2(viewUtils,parentInjector,declarationEl);
}