/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './camping';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/router/src/router';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/router/src/directives/router_link';
import * as import12 from '@angular/router/src/router_state';
import * as import13 from '@angular/common/src/location/location_strategy';
import * as import14 from '@angular/core/src/security';
var renderType_Camping_Host:import0.RenderComponentType = (null as any);
class _View_Camping_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Camping_0_4:import3.Camping;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Camping_Host0,renderType_Camping_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('camping',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Camping0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Camping_0_4 = new import3.Camping(this.parentInjector.get(import8.Router));
    this._appEl_0.initComponent(this._Camping_0_4,[],compView_0);
    compView_0.create(this._Camping_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.Camping) && (0 === requestNodeIndex))) { return this._Camping_0_4; }
    return notFoundResult;
  }
}
function viewFactory_Camping_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_Camping_Host === (null as any))) { (renderType_Camping_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_Camping_Host0(viewUtils,parentInjector,declarationEl);
}
export const CampingNgFactory:import10.ComponentFactory<import3.Camping> = new import10.ComponentFactory<import3.Camping>('camping',viewFactory_Camping_Host0,import3.Camping);
const styles_Camping:any[] = [];
var renderType_Camping:import0.RenderComponentType = (null as any);
class _View_Camping0 extends import1.AppView<import3.Camping> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _RouterLinkWithHref_22_3:import11.RouterLinkWithHref;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _el_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _el_75:any;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _el_79:any;
  _el_80:any;
  _text_81:any;
  _text_82:any;
  _text_83:any;
  _text_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _text_88:any;
  _el_89:any;
  _text_90:any;
  _el_91:any;
  _text_92:any;
  _text_93:any;
  _el_94:any;
  _text_95:any;
  _el_96:any;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _text_100:any;
  _el_101:any;
  _text_102:any;
  _text_103:any;
  _el_104:any;
  _text_105:any;
  _el_106:any;
  _RouterLinkWithHref_106_3:import11.RouterLinkWithHref;
  _text_107:any;
  _text_108:any;
  _text_109:any;
  _text_110:any;
  _el_111:any;
  _text_112:any;
  _el_113:any;
  _text_114:any;
  _el_115:any;
  _RouterLinkWithHref_115_3:import11.RouterLinkWithHref;
  _text_116:any;
  _text_117:any;
  _text_118:any;
  _el_119:any;
  _text_120:any;
  _text_121:any;
  _el_122:any;
  _text_123:any;
  _el_124:any;
  _text_125:any;
  _el_126:any;
  _text_127:any;
  _text_128:any;
  _text_129:any;
  _el_130:any;
  _text_131:any;
  _el_132:any;
  _text_133:any;
  _text_134:any;
  _text_135:any;
  _el_136:any;
  _text_137:any;
  _el_138:any;
  _text_139:any;
  _text_140:any;
  _text_141:any;
  _text_142:any;
  _text_143:any;
  _text_144:any;
  _text_145:any;
  _el_146:any;
  _text_147:any;
  _el_148:any;
  _text_149:any;
  _text_150:any;
  _el_151:any;
  _text_152:any;
  _el_153:any;
  _text_154:any;
  _el_155:any;
  _RouterLinkWithHref_155_3:import11.RouterLinkWithHref;
  _text_156:any;
  _text_157:any;
  _el_158:any;
  _el_159:any;
  _RouterLinkWithHref_159_3:import11.RouterLinkWithHref;
  _text_160:any;
  _text_161:any;
  _text_162:any;
  _text_163:any;
  _text_164:any;
  _text_165:any;
  _text_166:any;
  _text_167:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Camping0,renderType_Camping,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'section',(null as any));
    this.renderer.setElementAttribute(this._el_0,'id','camping');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'article',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','container');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'h1',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Make the most of your marketing',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','container');
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'img',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','camp-icon');
    this.renderer.setElementAttribute(this._el_9,'src','resources/images/cloud.png');
    this._text_10 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_7,'h3',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Consistent emails skyrocket customer loyalty',(null as any));
    this._text_13 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_7,'p',(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n                Engaging with your customers on a regular basis promotes a healthy relationship. Your customers truly care about what\'s going on at your campground, be sure to let them know! Setting up automated email marketing really is not that hard, checkout Constant\n                Contact.\n            ',(null as any));
    this._text_16 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_7,'p',(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'\n                We here at OTB are partners with Constant Contact and can get you setup fast.\n              ',(null as any));
    this._text_19 = this.renderer.createText(this._el_7,'\n              ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_7,'img',(null as any));
    this.renderer.setElementAttribute(this._el_20,'alt','Constant Contact');
    this.renderer.setElementAttribute(this._el_20,'class','p-y-0 m-y-0');
    this.renderer.setElementAttribute(this._el_20,'src','resources/images/ctct.png');
    this.renderer.setElementAttribute(this._el_20,'style','width: 100%');
    this._text_21 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_7,'a',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','text-danger');
    this.renderer.setElementAttribute(this._el_22,'routerLink','/constant-contact');
    this._RouterLinkWithHref_22_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import8.Router),this.parentInjector.get(import12.ActivatedRoute),this.parentInjector.get(import13.LocationStrategy));
    this._text_23 = this.renderer.createText(this._el_22,'Click here to sign up for Constant Contact through OTB',(null as any));
    this._text_24 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','container');
    this._text_27 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'img',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','camp-icon');
    this.renderer.setElementAttribute(this._el_28,'src','resources/images/fire.png');
    this._text_29 = this.renderer.createText(this._el_26,'\n\n            ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_26,'h3',(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'3 secrets for happy customers',(null as any));
    this._text_32 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_26,'ul',(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'li',(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n                    ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'span',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','text-yell');
    this._text_38 = this.renderer.createText(this._el_37,'1.',(null as any));
    this._text_39 = this.renderer.createText(this._el_35,' Customer service. Nothing new here, having good customer service is so crucial no matter the circumstance.\n                ',(null as any));
    this._text_40 = this.renderer.createText(this._el_33,'\n\n                ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_33,'li',(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'\n                    ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_41,'span',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','text-yell');
    this._text_44 = this.renderer.createText(this._el_43,'2.',(null as any));
    this._text_45 = this.renderer.createText(this._el_41,' Make it easy to reserve a campground. Give campers multiple ways to secure spots at your campground. This could be over the phone, through a website, via an app, the more gateways to get to you the\n                    better. A\n                ',(null as any));
    this._text_46 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_33,'li',(null as any));
    this._el_48 = this.renderer.createElement(this._el_47,'span',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','text-yell');
    this._text_49 = this.renderer.createText(this._el_48,'3.',(null as any));
    this._text_50 = this.renderer.createText(this._el_47,' Email marketing. Steady communication can be the key to success.',(null as any));
    this._text_51 = this.renderer.createText(this._el_33,'\n            ',(null as any));
    this._text_52 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_26,'p',(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'\n\n            ',(null as any));
    this._text_55 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._text_56 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_57,'class','container');
    this._text_58 = this.renderer.createText(this._el_57,'\n            ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_57,'img',(null as any));
    this.renderer.setElementAttribute(this._el_59,'class','camp-icon');
    this.renderer.setElementAttribute(this._el_59,'src','resources/images/stream.png');
    this._text_60 = this.renderer.createText(this._el_57,'\n            ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_57,'h3',(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'Add another stream of revenue to your campground',(null as any));
    this._text_63 = this.renderer.createText(this._el_57,'\n            ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_57,'p',(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'\n                Let\'s face it, in this day and age your customers are on the web constantly. Questions need answers, your customers are asking.\n            ',(null as any));
    this._text_66 = this.renderer.createText(this._el_57,'\n\n            ',(null as any));
    this._el_67 = this.renderer.createElement(this._el_57,'ul',(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'\n                ',(null as any));
    this._el_69 = this.renderer.createElement(this._el_67,'li',(null as any));
    this._el_70 = this.renderer.createElement(this._el_69,'span',(null as any));
    this.renderer.setElementAttribute(this._el_70,'class','text-yell');
    this._text_71 = this.renderer.createText(this._el_70,'-',(null as any));
    this._text_72 = this.renderer.createText(this._el_69,' Where are we going camping this weekend?',(null as any));
    this._text_73 = this.renderer.createText(this._el_67,'\n                ',(null as any));
    this._el_74 = this.renderer.createElement(this._el_67,'li',(null as any));
    this._el_75 = this.renderer.createElement(this._el_74,'span',(null as any));
    this.renderer.setElementAttribute(this._el_75,'class','text-yell');
    this._text_76 = this.renderer.createText(this._el_75,'-',(null as any));
    this._text_77 = this.renderer.createText(this._el_74,' To find the best answer to that question, 9/10 campers will go to google and start searching for campgrounds to brainstorm ideas.',(null as any));
    this._text_78 = this.renderer.createText(this._el_67,'\n                ',(null as any));
    this._el_79 = this.renderer.createElement(this._el_67,'li',(null as any));
    this._el_80 = this.renderer.createElement(this._el_79,'span',(null as any));
    this.renderer.setElementAttribute(this._el_80,'class','text-yell');
    this._text_81 = this.renderer.createText(this._el_80,'-',(null as any));
    this._text_82 = this.renderer.createText(this._el_79,' Will your campground be on there? And if so, can you reserve a site from your \'site\'?',(null as any));
    this._text_83 = this.renderer.createText(this._el_67,'\n            ',(null as any));
    this._text_84 = this.renderer.createText(this._el_57,'\n        ',(null as any));
    this._text_85 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_86 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_86,'class','container');
    this._text_87 = this.renderer.createText(this._el_86,'\n            ',(null as any));
    this._text_88 = this.renderer.createText(this._el_86,'\n            ',(null as any));
    this._el_89 = this.renderer.createElement(this._el_86,'img',(null as any));
    this.renderer.setElementAttribute(this._el_89,'class','camp-icon');
    this.renderer.setElementAttribute(this._el_89,'src','resources/images/teepee.png');
    this._text_90 = this.renderer.createText(this._el_86,'\n\n            ',(null as any));
    this._el_91 = this.renderer.createElement(this._el_86,'h3',(null as any));
    this._text_92 = this.renderer.createText(this._el_91,'Why your campground needs a website',(null as any));
    this._text_93 = this.renderer.createText(this._el_86,'\n            ',(null as any));
    this._el_94 = this.renderer.createElement(this._el_86,'div',(null as any));
    this.renderer.setElementAttribute(this._el_94,'class','row');
    this._text_95 = this.renderer.createText(this._el_94,'\n                ',(null as any));
    this._el_96 = this.renderer.createElement(this._el_94,'div',(null as any));
    this.renderer.setElementAttribute(this._el_96,'class','col col-lg-6');
    this._text_97 = this.renderer.createText(this._el_96,'\n                    ',(null as any));
    this._el_98 = this.renderer.createElement(this._el_96,'p',(null as any));
    this._text_99 = this.renderer.createText(this._el_98,'\n                        Having necessary information about your campground handy and easy to find on the internet can go a long way. You don\'t need to have a full featured, all the bells and whistles website. A simple, elegant to the point website can be easier to navigate and\n                        an overall better experience for your end user.\n                    ',(null as any));
    this._text_100 = this.renderer.createText(this._el_96,'\n                    ',(null as any));
    this._el_101 = this.renderer.createElement(this._el_96,'p',(null as any));
    this._text_102 = this.renderer.createText(this._el_101,'Do more with less on your website. Clean, easy to read websites allow visitors to get to the most important information quickly. Allow visitors to easily engage and navigate your website. Don’t just share information, allow visitors\n                        to take action.',(null as any));
    this._text_103 = this.renderer.createText(this._el_96,'\n                    ',(null as any));
    this._el_104 = this.renderer.createElement(this._el_96,'p',(null as any));
    this._text_105 = this.renderer.createText(this._el_104,'\n                        A website can be a gathering place of information. Visitors can interact with your site, which can expand to integrate with other tools you use on a daily basis like Constant Contact and Quickbooks. Using valuable integrations can eliminate manual data\n                        entry that eats up a lot of your time. Sign up ',(null as any));
    this._el_106 = this.renderer.createElement(this._el_104,'a',(null as any));
    this.renderer.setElementAttribute(this._el_106,'routerLink','/');
    this._RouterLinkWithHref_106_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import8.Router),this.parentInjector.get(import12.ActivatedRoute),this.parentInjector.get(import13.LocationStrategy));
    this._text_107 = this.renderer.createText(this._el_106,'here',(null as any));
    this._text_108 = this.renderer.createText(this._el_104,' for a free consultation on streamlining how you interact with your customers.\n                    ',(null as any));
    this._text_109 = this.renderer.createText(this._el_96,'\n                ',(null as any));
    this._text_110 = this.renderer.createText(this._el_94,'\n                ',(null as any));
    this._el_111 = this.renderer.createElement(this._el_94,'div',(null as any));
    this.renderer.setElementAttribute(this._el_111,'class','col col-lg-6');
    this._text_112 = this.renderer.createText(this._el_111,'\n                    ',(null as any));
    this._el_113 = this.renderer.createElement(this._el_111,'p',(null as any));
    this._text_114 = this.renderer.createText(this._el_113,'\n                        If you want to be accessible, you simply need a website. Get the ball rolling, here at ',(null as any));
    this._el_115 = this.renderer.createElement(this._el_113,'a',(null as any));
    this.renderer.setElementAttribute(this._el_115,'routerLink','/');
    this._RouterLinkWithHref_115_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import8.Router),this.parentInjector.get(import12.ActivatedRoute),this.parentInjector.get(import13.LocationStrategy));
    this._text_116 = this.renderer.createText(this._el_115,'otb',(null as any));
    this._text_117 = this.renderer.createText(this._el_113,' we can get you on your feet in no time. Down the road you can expand and add in features. You don\'t have to commit\n                        all at once.\n                    ',(null as any));
    this._text_118 = this.renderer.createText(this._el_111,'\n                    ',(null as any));
    this._el_119 = this.renderer.createElement(this._el_111,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_119,'class','p-b-0 m-b-0');
    this._text_120 = this.renderer.createText(this._el_119,'\n                      Visualize the possibilities\n                    ',(null as any));
    this._text_121 = this.renderer.createText(this._el_111,'\n                    ',(null as any));
    this._el_122 = this.renderer.createElement(this._el_111,'ul',(null as any));
    this._text_123 = this.renderer.createText(this._el_122,'\n                        ',(null as any));
    this._el_124 = this.renderer.createElement(this._el_122,'li',(null as any));
    this._text_125 = this.renderer.createText(this._el_124,'\n                            ',(null as any));
    this._el_126 = this.renderer.createElement(this._el_124,'span',(null as any));
    this.renderer.setElementAttribute(this._el_126,'class','text-yell');
    this._text_127 = this.renderer.createText(this._el_126,'-',(null as any));
    this._text_128 = this.renderer.createText(this._el_124,' Reward tracking Increase Customer Service\n                        ',(null as any));
    this._text_129 = this.renderer.createText(this._el_122,'\n                        ',(null as any));
    this._el_130 = this.renderer.createElement(this._el_122,'li',(null as any));
    this._text_131 = this.renderer.createText(this._el_130,'\n                            ',(null as any));
    this._el_132 = this.renderer.createElement(this._el_130,'span',(null as any));
    this.renderer.setElementAttribute(this._el_132,'class','text-yell');
    this._text_133 = this.renderer.createText(this._el_132,'-',(null as any));
    this._text_134 = this.renderer.createText(this._el_130,' Make a request via the app for better tracking of needs of your customers while they are visiting.\n                        ',(null as any));
    this._text_135 = this.renderer.createText(this._el_122,'\n                        ',(null as any));
    this._el_136 = this.renderer.createElement(this._el_122,'li',(null as any));
    this._text_137 = this.renderer.createText(this._el_136,'\n                            ',(null as any));
    this._el_138 = this.renderer.createElement(this._el_136,'span',(null as any));
    this.renderer.setElementAttribute(this._el_138,'class','text-yell');
    this._text_139 = this.renderer.createText(this._el_138,'-',(null as any));
    this._text_140 = this.renderer.createText(this._el_136,' Mobile Reservations via the app\n                        ',(null as any));
    this._text_141 = this.renderer.createText(this._el_122,'\n                    ',(null as any));
    this._text_142 = this.renderer.createText(this._el_111,'\n                ',(null as any));
    this._text_143 = this.renderer.createText(this._el_94,'\n            ',(null as any));
    this._text_144 = this.renderer.createText(this._el_86,'\n        ',(null as any));
    this._text_145 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_146 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_146,'class','container');
    this._text_147 = this.renderer.createText(this._el_146,'\n            ',(null as any));
    this._el_148 = this.renderer.createElement(this._el_146,'h3',(null as any));
    this._text_149 = this.renderer.createText(this._el_148,'Helpful links',(null as any));
    this._text_150 = this.renderer.createText(this._el_146,'\n            ',(null as any));
    this._el_151 = this.renderer.createElement(this._el_146,'ul',(null as any));
    this._text_152 = this.renderer.createText(this._el_151,'\n                ',(null as any));
    this._el_153 = this.renderer.createElement(this._el_151,'li',(null as any));
    this._text_154 = this.renderer.createText(this._el_153,'\n                    ',(null as any));
    this._el_155 = this.renderer.createElement(this._el_153,'a',(null as any));
    this.renderer.setElementAttribute(this._el_155,'class','text-danger');
    this.renderer.setElementAttribute(this._el_155,'href','#');
    this.renderer.setElementAttribute(this._el_155,'routerLink','/constant-contact');
    this._RouterLinkWithHref_155_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import8.Router),this.parentInjector.get(import12.ActivatedRoute),this.parentInjector.get(import13.LocationStrategy));
    this._text_156 = this.renderer.createText(this._el_155,'Constant Contact Registration',(null as any));
    this._text_157 = this.renderer.createText(this._el_151,'\n                ',(null as any));
    this._el_158 = this.renderer.createElement(this._el_151,'li',(null as any));
    this._el_159 = this.renderer.createElement(this._el_158,'a',(null as any));
    this.renderer.setElementAttribute(this._el_159,'class','text-danger');
    this.renderer.setElementAttribute(this._el_159,'href','#');
    this.renderer.setElementAttribute(this._el_159,'routerLink','/');
    this._RouterLinkWithHref_159_3 = new import11.RouterLinkWithHref(this.parentInjector.get(import8.Router),this.parentInjector.get(import12.ActivatedRoute),this.parentInjector.get(import13.LocationStrategy));
    this._text_160 = this.renderer.createText(this._el_159,'Outside The Box Home',(null as any));
    this._text_161 = this.renderer.createText(this._el_158,'\n                ',(null as any));
    this._text_162 = this.renderer.createText(this._el_151,'\n            ',(null as any));
    this._text_163 = this.renderer.createText(this._el_146,'\n        ',(null as any));
    this._text_164 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_165 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_166 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_167 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_22,'click',this.eventHandler(this._handle_click_22_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_106,'click',this.eventHandler(this._handle_click_106_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_115,'click',this.eventHandler(this._handle_click_115_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_155,'click',this.eventHandler(this._handle_click_155_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_159,'click',this.eventHandler(this._handle_click_159_0.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._el_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._el_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._el_79,
      this._el_80,
      this._text_81,
      this._text_82,
      this._text_83,
      this._text_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._text_93,
      this._el_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._text_100,
      this._el_101,
      this._text_102,
      this._text_103,
      this._el_104,
      this._text_105,
      this._el_106,
      this._text_107,
      this._text_108,
      this._text_109,
      this._text_110,
      this._el_111,
      this._text_112,
      this._el_113,
      this._text_114,
      this._el_115,
      this._text_116,
      this._text_117,
      this._text_118,
      this._el_119,
      this._text_120,
      this._text_121,
      this._el_122,
      this._text_123,
      this._el_124,
      this._text_125,
      this._el_126,
      this._text_127,
      this._text_128,
      this._text_129,
      this._el_130,
      this._text_131,
      this._el_132,
      this._text_133,
      this._text_134,
      this._text_135,
      this._el_136,
      this._text_137,
      this._el_138,
      this._text_139,
      this._text_140,
      this._text_141,
      this._text_142,
      this._text_143,
      this._text_144,
      this._text_145,
      this._el_146,
      this._text_147,
      this._el_148,
      this._text_149,
      this._text_150,
      this._el_151,
      this._text_152,
      this._el_153,
      this._text_154,
      this._el_155,
      this._text_156,
      this._text_157,
      this._el_158,
      this._el_159,
      this._text_160,
      this._text_161,
      this._text_162,
      this._text_163,
      this._text_164,
      this._text_165,
      this._text_166,
      this._text_167
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.RouterLinkWithHref) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._RouterLinkWithHref_22_3; }
    if (((token === import11.RouterLinkWithHref) && ((106 <= requestNodeIndex) && (requestNodeIndex <= 107)))) { return this._RouterLinkWithHref_106_3; }
    if (((token === import11.RouterLinkWithHref) && ((115 <= requestNodeIndex) && (requestNodeIndex <= 116)))) { return this._RouterLinkWithHref_115_3; }
    if (((token === import11.RouterLinkWithHref) && ((155 <= requestNodeIndex) && (requestNodeIndex <= 156)))) { return this._RouterLinkWithHref_155_3; }
    if (((token === import11.RouterLinkWithHref) && ((159 <= requestNodeIndex) && (requestNodeIndex <= 160)))) { return this._RouterLinkWithHref_159_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = '/constant-contact';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_22_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_22_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_4:any = '/';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._RouterLinkWithHref_106_3.routerLink = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_106_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_7:any = '/';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._RouterLinkWithHref_115_3.routerLink = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_115_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_10:any = '/constant-contact';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._RouterLinkWithHref_155_3.routerLink = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_155_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_13:any = '/';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._RouterLinkWithHref_159_3.routerLink = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_159_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._RouterLinkWithHref_22_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_22,'href',this.viewUtils.sanitizer.sanitize(import14.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._RouterLinkWithHref_106_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_106,'href',this.viewUtils.sanitizer.sanitize(import14.SecurityContext.URL,currVal_5));
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._RouterLinkWithHref_115_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_115,'href',this.viewUtils.sanitizer.sanitize(import14.SecurityContext.URL,currVal_8));
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this._RouterLinkWithHref_155_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementProperty(this._el_155,'href',this.viewUtils.sanitizer.sanitize(import14.SecurityContext.URL,currVal_11));
      this._expr_11 = currVal_11;
    }
    const currVal_14:any = this._RouterLinkWithHref_159_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementProperty(this._el_159,'href',this.viewUtils.sanitizer.sanitize(import14.SecurityContext.URL,currVal_14));
      this._expr_14 = currVal_14;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_22_3.ngOnDestroy();
    this._RouterLinkWithHref_106_3.ngOnDestroy();
    this._RouterLinkWithHref_115_3.ngOnDestroy();
    this._RouterLinkWithHref_155_3.ngOnDestroy();
    this._RouterLinkWithHref_159_3.ngOnDestroy();
  }
  private _handle_click_22_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_22_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_106_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_106_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_115_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_115_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_155_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_155_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_159_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_159_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Camping0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.Camping> {
  if ((renderType_Camping === (null as any))) { (renderType_Camping = viewUtils.createRenderComponentType('/Users/oliviatrimble/Workspaces/otb/web/app/pages/camping/camping.html',0,import9.ViewEncapsulation.None,styles_Camping,{})); }
  return new _View_Camping0(viewUtils,parentInjector,declarationEl);
}